### ISSUE TITLE
Sails v0.12 Reg 

### ISSUE THREAD

**Issue by bdschr** [waterlock/waterlock#127]
Having problems when I make a post request on auth/register. For some reason if I get a error message the whole application crashes with this error. Even on a clean sails-js waterlock installation. Currently using it with JWT.

```
http_outgoing.js:344
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.res.setHeader (/Users/david/Data/git/src/ns_project/node_modules/sails/node_modules/express/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.res.set.res.header (/Users/david/Data/git/src/ns_project/node_modules/sails/node_modules/express/lib/response.js:595:10)
    at ServerResponse.res.send (/Users/david/Data/git/src/ns_project/node_modules/sails/node_modules/express/lib/response.js:151:12)
    at ServerResponse.res.json (/Users/david/Data/git/src/ns_project/node_modules/sails/node_modules/express/lib/response.js:237:15)
    at ServerResponse.jsonx (/Users/david/Data/git/src/ns_project/node_modules/sails/lib/hooks/responses/index.js:223:21)
    at Object.forbidden (/Users/david/Data/git/src/ns_project/api/responses/forbidden.js:41:16)
    at ServerResponse.wrapper [as forbidden] (/Users/david/Data/git/src/ns_project/node_modules/sails/node_modules/lodash/index.js:3095:19)
    at Object.registerFailure (/Users/david/Data/git/src/ns_project/node_modules/waterlock/lib/cycle.js:121:13)
    at /Users/david/Data/git/src/ns_project/node_modules/waterlock-local-auth/lib/controllers/actions/register.js:28:27
    at Object._attachAuthToUser (/Users/david/Data/git/src/ns_project/node_modules/waterlock/lib/engine.js:70:9)
    at /Users/david/Data/git/src/ns_project/node_modules/waterlock/lib/engine.js:100:16
    at wrapper (/Users/david/Data/git/src/ns_project/node_modules/sails/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/Users/david/Data/git/src/ns_project/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/Users/david/Data/git/src/ns_project/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at callback.success (/Users/david/Data/git/src/ns_project/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
```

**Comment by bdschr** [comment]
Didn't see https://github.com/waterlock/waterlock-local-auth/pull/52

**Comment by bdschr** [comment]
Still having a problem with cycle.js when make a post request with a attribute that doesn't pass validation. Similar crash in cycle.js on

`at Object.registerFailure (/Users/david/Data/git/src/ns_project/node_modules/waterlock/lib/cycle.js:121:13)`

**Comment by NOaMTL** [comment]
same issue for me

**Comment by re757575** [comment]
+1

**Comment by andyngdz** [comment]
Same issue for me
