### ISSUE TITLE
Fresh project breaks when lifting project due to ResetToken.js

### ISSUE THREAD

**Issue by reshadf** [waterlock/waterlock#143]
Hi I have created a new Sails project and installed waterlock with local-auth and facebook-auth. After that I added my facebook key and secret and changed the settings accordingly in waterlock.js. After trying to start up the project with sails lift I get a error that says the following:

>error: A hook (`orm`) failed to load!
error: `include-all` attempted to `require(/Users/username/Sites/project-api/api/models/ResetToken.js)`, but an error occurred::
Details:TypeError: Cannot read property 'attributes' of undefined

I havent done any modifications to this model though.. 

npm -v = 3.10.7
sails -v = 0.12.7

Edit: I recreated the same thing step by step and I figured out that it breaks after I install and configure the facebook auth.

**Comment by andaluz** [comment]
I really like it (haven't tested yet).

**Comment by jimmysyss** [comment]
I am getting similar issue, the full stack is as followed. 

> /usr/local/bin/node app.js
error: A hook (`orm`) failed to load!
error: Error: Trying to access a collection resettoken that is not defined.
    at ForeignKeys.findPrimaryKey (/usr/local/lib/node_modules/sails/node_modules/waterline-schema/lib/waterline-schema/foreignKeys.js:82:11)
    at ForeignKeys.replaceKeys (/usr/local/lib/node_modules/sails/node_modules/waterline-schema/lib/waterline-schema/foreignKeys.js:53:27)
    at new ForeignKeys (/usr/local/lib/node_modules/sails/node_modules/waterline-schema/lib/waterline-schema/foreignKeys.js:30:10)
    at new module.exports (/usr/local/lib/node_modules/sails/node_modules/waterline-schema/lib/waterline-schema.js:30:17)
    at Waterline.initialize (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:122:17)
    at buildWaterlineOntology (/usr/local/lib/node_modules/sails/node_modules/sails-hook-orm/lib/build-waterline-ontology.js:45:19)
    at Array.async.auto._buildOntology (/usr/local/lib/node_modules/sails/node_modules/sails-hook-orm/lib/initialize.js:388:7)
    at listener (/usr/local/lib/node_modules/sails/node_modules/sails-hook-orm/node_modules/async/lib/async.js:605:42)
    at /usr/local/lib/node_modules/sails/node_modules/sails-hook-orm/node_modules/async/lib/async.js:544:17
    at _arrayEach (/usr/local/lib/node_modules/sails/node_modules/sails-hook-orm/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/usr/local/lib/node_modules/sails/node_modules/sails-hook-orm/node_modules/async/lib/async.js:543:13)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)


>

**Comment by alexandrepossebom** [comment]
I have same issue here

**Comment by davidecampello** [comment]
Hi, have you found a solution?
Thanks
