### ISSUE TITLE
Suggestion: Use bcrypt-nodejs instead of bcrypt

### ISSUE THREAD

**Issue by blah238** [waterlock/waterlock#4]
For Windows users, installing and configuring everything needed to build bcrypt is insane: http://stackoverflow.com/questions/14573488/error-compiling-bcrypt-node-js

Please consider switching to the native JavaScript port: https://github.com/shaneGirish/bcrypt-nodejs

Windows users will thank you for this :)

**Comment by mazemax** [comment]
This issue is still not resolved. It's a question mark on stability of waterlock package.
Following are the debug logs.

```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\user\Desktop\game\waterlog>npm install waterlock
waterlog@0.0.0 C:\Users\user\Desktop\game\waterlog
`-- waterlock@0.1.2-rc1
  +-- jwt-simple@0.3.1
  +-- lodash@3.8.0
  +-- moment@2.10.6
  `-- winston@1.0.2
    +-- async@1.0.0
    +-- colors@1.0.3
    `-- pkginfo@0.3.1


C:\Users\user\Desktop\game\waterlog>npm install waterlock-local-auth
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer

> bcrypt@0.8.7 install C:\Users\user\Desktop\game\waterlog\node_modules\bcrypt
> node-gyp rebuild


C:\Users\user\Desktop\game\waterlog\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modul
es\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. 
Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:
\Users\user\Desktop\game\waterlog\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\Desktop\game\waterlog\node_modules\bcrypt
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
waterlog@0.0.0 C:\Users\user\Desktop\game\waterlog
+-- jade@1.11.0  extraneous
`-- nodemailer@1.4.0  extraneous

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "waterlock-local-auth"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\Desktop\game\waterlog\npm-debug.log

```

[npm-debug.txt](https://github.com/waterlock/waterlock/files/415026/npm-debug.txt)

**Comment by wayne-o** [comment]
I will be able to dedicate more time to this project in sept onwards - been
a bit busy with life etc recently
