### ISSUE TITLE
Migrate step triggered upon installation: sails can not be started

### ISSUE THREAD

**Issue by robertgdev** [waterlock/waterlock#51]
Let me preface by telling you that I'm just getting started with NodeJS and Sails; there may be something very stupid I'm doing wrong. 

I've generated a new Sail app and have installed waterlock and when I'm trying to start sails, I get the 

`Excuse my interruption, but it looks like this app
 does not have a project-wide "migrate" setting configured yet.
 (perhaps this is the first time you're lifting it with models?)`

dialog. When I chose any option (1, 2 or 3) I get the following error:

```
usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/foreignKeys.js:82
    throw new Error('Trying to access a collection ' + collection + ' that is 
          ^
Error: Trying to access a collection resettoken that is not defined.
    at ForeignKeys.findPrimaryKey (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/foreignKeys.js:82:11)
    at ForeignKeys.replaceKeys (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/foreignKeys.js:53:27)
    at new ForeignKeys (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/foreignKeys.js:30:10)
    at new module.exports (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema.js:30:17)
    at Waterline.initialize (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:106:17)
    at buildORM (/usr/local/lib/node_modules/sails/lib/hooks/orm/build-orm.js:48:15)
    at Array.async.auto.instantiatedCollections [as 1] (/usr/local/lib/node_modules/sails/lib/hooks/orm/index.js:191:11)
    at listener (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:465:46)
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:419:17
```

Like I said above, I have no idea if this is a bug or something stupid I'm doing but at this point I'm stuck. I'd appreciate any hints you have as to how to resolve this.

**Comment by tenzan** [comment]
Hello!

For some reason, I'm having same issue when deploying `SailsJS` app in heroku.
Here's log details: https://gist.github.com/tenzan/0682f0c34cc7e5d8eebc

And here's my repo https://github.com/tenzan/sails-api-server/tree/heroku

Thanks.
