### ISSUE TITLE
Best way to generate a token for testing

### ISSUE THREAD

**Issue by robksawyer** [waterlock/waterlock#66]
I tried using the method that you used in the test folder of Waterlock, but I keep getting the following error when using this token. Is there a better way to generate tokens for testing? 

When using a fixture waterlock.config file I get:

```
error: Error: Signature verification failed
    at Object.jwt_decode [as decode] (/Users/robsawyer/Sites/minnow-back/node_modules/waterlock/node_modules/jwt-simple/lib/jwt.js:83:13)
```

When trying to use the app's `config/waterlock.js` I get:

```
error: TypeError: Cannot read property 'models' of undefined
    at Waterlock.User (/Users/robsawyer/Sites/minnow-back/node_modules/waterlock/lib/waterlock.js:38:20)
```

**Comment by rh0dium** [comment]
Hey Guys,

I'm at exactly this same point.  Even basic testing can continue.  I'm sure there is something we're doing wrong.  It looks like sails isn't even recognized.

     TypeError: Cannot read property 'models' of undefined at  Waterlock.Auth    
    (/Users/sklass/Documents/Projects/IC_Manage/gdp_server/node_modules/waterlock/lib/waterlock.js:34:20)

**Comment by rh0dium** [comment]
Hey I just found something that gets us around this.

In your `bootstrap.tests.js` modify the following line to put sails into the global namespace.

    var Sails = global.sails = require('sails');

Ref:
https://gist.github.com/rh0dium/cd6336977d2e74635f00
