### ISSUE TITLE
fresh setup on win7 64

### ISSUE THREAD

**Issue by syarul** [waterlock/waterlock#69]
Is this the the correct setup, or do I miss something?

```
npm install waterlock
npm install waterlock-local-auth
node_modules\.bin\waterlock generate all
sails lift
```

The return error,

```
E:\distro\test-water\node_modules\waterlock\lib\methods.js:112
      throw error;
            ^
Error: Authentication method waterlock-local-auth could not be found.
Try running npm install waterlock-local-auth


    at Object._errorHandler (E:\distro\test-water\node_modules\waterlock\lib\methods.js:109:19)
    at Object._handleObjects (E:\distro\test-water\node_modules\waterlock\lib\methods.js:54:14)
    at Object.collect (E:\distro\test-water\node_modules\waterlock\lib\methods.js:33:19)
    at new Waterlock (E:\distro\test-water\node_modules\waterlock\lib\waterlock.js:19:50)
    at Object.<anonymous> (E:\distro\test-water\node_modules\waterlock\lib\index.js:8:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by nishanthk123** [comment]
Hi Vijay, 

How do you change the dependency to bcryptjs. Please help. I tried npm install bcryptjs and then npm install waterlock-local-auth but I get the same error.

**Comment by vijayrajasekaran** [comment]
@nishanthk123 Hey, i am not using waterlock-local-auth now. I hope someone here can help you out! Try manually downloading from git and then replace bcrypt with bycrptjs in package.json --> npm install. I am not sure if this will work, i am also a beginner in node.js

**Comment by jodonnell-broadsoft** [comment]
I'm still stuck on this. Anyone got any other ideas?

**Comment by syarul** [comment]
This the module for sails, so you need to install it on top sails application. First generate the app
```
sails new waterlock-test
npm install waterlock --save-dev
npm install waterlock-local-auth --save-dev
```

generate the api for the auth
```
./node_modules/.bin/waterlock generate all
```

create a new api
```
sails generate api post
```

and add this to post controller
```
module.exports = {
	restricted:function(req,res){
		return res.ok("visible only if authenticated");
	},	
	open:function(req,res){
		return res.ok("open public viewing");
	}
};
```

update/add policy within the api/policies folder for session auth
```
module.exports.policies = {

  '*': true,
  PostController:{
  	restricted:['sessionAuth'],
  	open:true
  }
};
```

you can test the policy by navigating to
```
http://localhost:1337/post/open
http://localhost:1337/post/restricted
```
so you can create that using POSTMAN chrome extension to generate the user and test it

**Comment by wayne-o** [comment]
Also bcrypt was recently updated to fix the issues surrounding that - you shouldn't need to swap to bcryptjs any more
