### ISSUE TITLE
/auth/register action?

### ISSUE THREAD

**Issue by jamesdixon** [waterlock/waterlock#83]
Hi,

I've successfully implemented authentication using Sails/Waterlock and Ember. The one thing I'm a bit confused on is how to register a user if you don't have the `createOnNotFound` property set to `true`. I attempted to use this, but it's causing me some problems as I'm using Ember Simple Auth and don't have a way (that I know of) to authenticate from the data returned by Waterlock after a user signs up. I could just redirect to my login page and have them login again which creates another JWT token, but it seems unnecessary. I see a `register` action mentioned in the `waterlock.js` config file; is there a hook to simply register a user without logging them in?

Best,
James

**Comment by elennaro** [comment]
I also didn't figure out how to do this.
When I set `createOnNotFound` to `false` and try to use `http://localhost:1337/auth/register?email=a@s.d&password=12345678` to register a new user. I've got 500 error:

````
error: Sending 500 ("Server Error") response: 
 TypeError: undefined is not a function
    at Object.module.exports (D:\temp\sails-waterlock\node_modules\waterlock\lib\controllers\actions\register.js:25:44)
    at bound (C:\Users\sandres\AppData\Roaming\npm\node_modules\sails\node_modules\lodash\dist\lodash.js:729:21)
    at routeTargetFnWrapper (C:\Users\sandres\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:179:5)
    at callbacks (C:\Users\sandres\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\index.js:164:37)
    at param (C:\Users\sandres\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\index.js:138:11)
    at param (C:\Users\sandres\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\index.js:135:11)
    at pass (C:\Users\sandres\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\index.js:145:5)
    at nextRoute (C:\Users\sandres\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\index.js:100:7)
    at callbacks (C:\Users\sandres\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\index.js:167:11)
    at C:\Users\sandres\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:187:7
    at alwaysAllow (C:\Users\sandres\AppData\Roaming\npm\node_modules\sails\lib\hooks\policies\index.js:207:11)
    at routeTargetFnWrapper (C:\Users\sandres\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:179:5)
    at callbacks (C:\Users\sandres\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\index.js:164:37)
    at param (C:\Users\sandres\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\index.js:138:11)
    at param (C:\Users\sandres\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\index.js:135:11)
    at pass (C:\Users\sandres\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\index.js:145:5) [TypeError: undefined is not a function]
````

Sails v 0.11, Waterlock v 0.1.0

**Comment by jamesdixon** [comment]
@elennaro I too had the same error. For the time being, I just overrode the `register` action in the `AuthController` to handle registration at a separate URL.

**Comment by elennaro** [comment]
Thanks @jamesdixon. I've ended up with [this](http://stackoverflow.com/questions/29944905/sails-js-waterlock-auth-register-causes-error-500/29949255#29949255) solution.

**Comment by s-devaney** [comment]
This functionality is now included in waterlock-local-auth, should this issue be closed now?

**Comment by wayne-o** [comment]
can do - but we need to be able to push all this to NPM and I don't have
access
